package rcontrolstationcomm;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("RControlStationComm") 
public class ROUTE_POINT extends StructObject {
	private static final long serialVersionUID = 1L;
	
	@Field(0) 
	public double px() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public ROUTE_POINT px(double px) {
		this.io.setDoubleField(this, 0, px);
		return this;
	}
	@Field(1) 
	public double py() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public ROUTE_POINT py(double py) {
		this.io.setDoubleField(this, 1, py);
		return this;
	}
	@Field(2) 
	public double speed() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public ROUTE_POINT speed(double speed) {
		this.io.setDoubleField(this, 2, speed);
		return this;
	}
	@Field(3) 
	public int time() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public ROUTE_POINT time(int time) {
		this.io.setIntField(this, 3, time);
		return this;
	}
	public ROUTE_POINT() {
		super();
	}
	public ROUTE_POINT(Pointer pointer) {
		super(pointer);
	}
}

