#!/bin/bash

# Exit on error
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
FWPATH="Embedded/RC_Controller"

cd $DIR
git pull

cd $FWPATH
touch conf_general.h
make -j4 build_args="$@" upload

