#!/bin/bash

# Exit on error
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
FWPATH="Embedded/RC_Controller"

cd $DIR
cd $FWPATH

# VCC
touch conf_general.h
make -j4 build_args="-DMAIN_MODE=MAIN_MODE_CAR -DUBLOX_EN=0"
mv build/rc_controller.bin precompiled/fw_vcc.bin

# Tero
touch conf_general.h
make -j4 build_args="-DMAIN_MODE=MAIN_MODE_CAR -DCAR_TERO -DUBLOX_EN=1 -DBOARD_YAW_ROT=90.0"
mv build/rc_controller.bin precompiled/fw_tero.bin

# rise_ubx
touch conf_general.h
make -j4 build_args="-DMAIN_MODE=MAIN_MODE_CAR -DUBLOX_EN=1 -DBOARD_YAW_ROT=-90.0"
mv build/rc_controller.bin precompiled/fw_rise_ubx.bin

