#!/bin/bash

# Exit on error
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

sudo cp Linux/udev/10-rise_sdvp.rules /etc/udev/rules.d
sudo cp Linux/udev/49-stlinkv2.rules /etc/udev/rules.d

