#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
CFG=$DIR/oo_rpi3.cfg

PI_VERSION=""
while IFS= read -r -d '' substring || [[ $substring ]]; do
    PI_VERSION+="$substring"
done </proc/device-tree/model

if [[ $PI_VERSION == 'Raspberry Pi 4'* ]]; then
    CFG=$DIR/oo_rpi4.cfg
fi

sudo openocd -f $CFG -c "transport select swd" -c "set CHIPNAME stm32f4x" -f "target/stm32f4x.cfg" -c "reset_config  srst_only srst_push_pull" -c "adapter_nsrst_delay 200" -c "adapter_nsrst_assert_width 200" -c "init;reset;exit"

