#!/bin/bash
sudo openocd -f interface/raspberrypi2-native.cfg -c "transport select swd" -c "set CHIPNAME stm32f4x" -f "target/stm32f4x.cfg" -c "reset_config  srst_only srst_push_pull" -c "adapter_nsrst_delay 100" -c "adapter_nsrst_assert_width 100" -c "bcm2835gpio_swd_nums 25 24" -c "bcm2835gpio_srst_num 18" -c "init;reset;exit"

