#!/bin/bash

# Exit on error
set -e

if [[ $1 == @(vcc|tero|rise_ubx|drangen) ]]; then
    FW=fw_$1.bin
else
    echo No valid firmware specified. Please use
    echo ./upload_fw [fw]
    echo where [fw] can be vcc, tero, rise_ubx or drangen
    exit 1
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
FWPATH="Embedded/RC_Controller/precompiled"

cd $DIR

git pull

cd $FWPATH

openocd -f board/stm32f4discovery.cfg -c "reset_config trst_only combined" -c "program $FW verify reset exit 0x08000000"

