#ifndef RCONTROLSTATIONCOMM_GLOBAL_H
#define RCONTROLSTATIONCOMM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RCONTROLSTATIONCOMM_LIBRARY)
#  define RCONTROLSTATIONCOMMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RCONTROLSTATIONCOMMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RCONTROLSTATIONCOMM_GLOBAL_H
