#!/bin/bash

# Create directories
mkdir -p src/main/java
mkdir -p src/main/scala
mkdir -p src/main/resources
mkdir -p src/test/java
mkdir -p src/test/scala
mkdir -p src/test/resources
mkdir -p project

# Add sbteclipse to the project
echo 'addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")' > project/plugins.sbt

# Create the eclipse project
sbt eclipse

