#!/bin/bash

set -e

export ANDROID_HOME=/home/benjamin/Android
export ANDROID_NDK_HOST=linux-x86_64
export ANDROID_NDK_PLATFORM=android-23
export ANDROID_NDK_ROOT=$ANDROID_HOME/Ndk
export ANDROID_NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi
export ANDROID_NDK_TOOLCHAIN_VERSION=4.9
export ANDROID_NDK_TOOLS_PREFIX=arm-linux-androideabi
export ANDROID_SDK_ROOT=$ANDROID_HOME/Sdk
export ANDROID_API_VERSION=android-26

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export PATH=$PATH:$ANDROID_HOME/Sdk/tools:/usr/bin:$JAVA_HOME/bin

export PATH=/opt/Qt2/5.9.3/android_armv7/bin/:$PATH
rm -rf build/android/*

qmake -config release "CONFIG += release_android"
make clean
make -j8
make install INSTALL_ROOT=build/android/build
androiddeployqt --output build/android/build --input android-libRControlStation.so-deployment-settings.json --android-platform android-23
mv build/android/build/bin/QtApp-debug.apk build/android/RControlStation.apk
rm -rf build/android/build
rm -rf build/android/obj
rm -f build/android/libRControlStation.so

